/// Traduz o nome bruto de gênero/subgênero que a API de lookup do iTunes
/// devolve em `primaryGenreName` (inglês, granular — ex. "Comedy Fiction")
/// pra pt-BR. Cobre as categorias e subcategorias oficiais do Apple
/// Podcasts; nomes fora da lista voltam sem tradução (nunca perde a
/// informação, só fica em inglês no pior caso).
const Map<String, String> _genreLabelsPtBr = {
  'Arts': 'Artes',
  'Books': 'Livros',
  'Design': 'Design',
  'Fashion & Beauty': 'Moda e Beleza',
  'Food': 'Gastronomia',
  'Performing Arts': 'Artes Cênicas',
  'Visual Arts': 'Artes Visuais',
  'Business': 'Negócios',
  'Careers': 'Carreira',
  'Entrepreneurship': 'Empreendedorismo',
  'Investing': 'Investimentos',
  'Management': 'Gestão',
  'Marketing': 'Marketing',
  'Non-Profit': 'Sem Fins Lucrativos',
  'Comedy': 'Comédia',
  'Comedy Interviews': 'Comédia — Entrevistas',
  'Improv': 'Improviso',
  'Stand-Up': 'Stand-Up',
  'Education': 'Educação',
  'Courses': 'Cursos',
  'How To': 'Como Fazer',
  'Language Learning': 'Aprendizado de Idiomas',
  'Self-Improvement': 'Autodesenvolvimento',
  'Fiction': 'Ficção',
  'Comedy Fiction': 'Comédia de Ficção',
  'Drama': 'Drama',
  'Science Fiction': 'Ficção Científica',
  'Government': 'Governo',
  'History': 'História',
  'Health & Fitness': 'Saúde e Fitness',
  'Alternative Health': 'Saúde Alternativa',
  'Fitness': 'Fitness',
  'Medicine': 'Medicina',
  'Mental Health': 'Saúde Mental',
  'Nutrition': 'Nutrição',
  'Sexuality': 'Sexualidade',
  'Kids & Family': 'Infantil e Família',
  'Education for Kids': 'Educação Infantil',
  'Parenting': 'Maternidade e Paternidade',
  'Pets & Animals': 'Pets e Animais',
  'Stories for Kids': 'Histórias Infantis',
  'Leisure': 'Lazer',
  'Animation & Manga': 'Animação e Mangá',
  'Automotive': 'Automóveis',
  'Aviation': 'Aviação',
  'Crafts': 'Artesanato',
  'Games': 'Jogos',
  'Hobbies': 'Hobbies',
  'Home & Garden': 'Casa e Jardim',
  'Video Games': 'Videogames',
  'Music': 'Música',
  'Music Commentary': 'Música — Comentário',
  'Music History': 'História da Música',
  'Music Interviews': 'Música — Entrevistas',
  'News': 'Notícias',
  'Business News': 'Notícias de Negócios',
  'Daily News': 'Notícias do Dia',
  'Entertainment News': 'Notícias de Entretenimento',
  'News Commentary': 'Notícias — Comentário',
  'Politics': 'Política',
  'Sports News': 'Notícias de Esportes',
  'Tech News': 'Notícias de Tecnologia',
  'Religion & Spirituality': 'Religião e Espiritualidade',
  'Buddhism': 'Budismo',
  'Christianity': 'Cristianismo',
  'Hinduism': 'Hinduísmo',
  'Islam': 'Islamismo',
  'Judaism': 'Judaísmo',
  'Religion': 'Religião',
  'Spirituality': 'Espiritualidade',
  'Science': 'Ciência',
  'Astronomy': 'Astronomia',
  'Chemistry': 'Química',
  'Earth Sciences': 'Ciências da Terra',
  'Life Sciences': 'Ciências Biológicas',
  'Mathematics': 'Matemática',
  'Natural Sciences': 'Ciências Naturais',
  'Nature': 'Natureza',
  'Physics': 'Física',
  'Social Sciences': 'Ciências Sociais',
  'Society & Culture': 'Sociedade e Cultura',
  'Documentary': 'Documentário',
  'Personal Journals': 'Diários Pessoais',
  'Philosophy': 'Filosofia',
  'Places & Travel': 'Lugares e Viagens',
  'Relationships': 'Relacionamentos',
  'Sports': 'Esportes',
  'Baseball': 'Beisebol',
  'Basketball': 'Basquete',
  'Cricket': 'Críquete',
  'Fantasy Sports': 'Fantasy Sports',
  'Football': 'Futebol Americano',
  'Golf': 'Golfe',
  'Hockey': 'Hóquei',
  'Rugby': 'Rugby',
  'Running': 'Corrida',
  'Soccer': 'Futebol',
  'Swimming': 'Natação',
  'Tennis': 'Tênis',
  'Volleyball': 'Vôlei',
  'Wilderness': 'Vida Selvagem',
  'Wrestling': 'Luta Livre',
  'Technology': 'Tecnologia',
  'True Crime': 'True Crime',
  'TV & Film': 'TV e Cinema',
  'After Shows': 'Pós-Programa',
  'Film History': 'História do Cinema',
  'Film Interviews': 'Cinema — Entrevistas',
  'Film Reviews': 'Crítica de Cinema',
  'TV Reviews': 'Crítica de TV',
};

/// Traduz `rawGenre` (ex. `podcast.genre`, vindo direto do iTunes) pra
/// pt-BR. Devolve o valor original se não houver tradução conhecida.
String translateGenreLabel(String rawGenre) =>
    _genreLabelsPtBr[rawGenre] ?? rawGenre;
